---
- hosts: 192.168.2.0
  tasks:
  - name: REPORTS
    fetch:
            src: C:\Users\{{ansible_user}}\{{item}}.txt
            dest: /opt/windows-scan/reports/
            flat: yes
    with_items:
        - firewall
        - hostfile
        - admingroup
        - basicuserinfo
        - interfaces
        - shares
        - uac
        - usedport

  - name: COPY CSV REPORT
    fetch:
           src: C:\Users\{{ansible_user}}\results.csv
           dest: /opt/windows-scan/reports/
           flat: yes 

